CREATE DATABASE EMotion_DB;

USE EMotion_DB;

CREATE TABLE CarProducer_T (
	ID INT NOT NULL IDENTITY(1,1),
	Name VARCHAR(32),
	PRIMARY KEY (ID)
);

CREATE TABLE CarModel_T (
	ID INT NOT NULL IDENTITY(1,1),
	CarProducerID INT,
	Name VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE CarModel_T ADD CONSTRAINT CarModel_T_fk0 FOREIGN KEY (CarProducerID) REFERENCES CarProducer_T(ID);

CREATE TABLE CarInfo_T (
	ID INT NOT NULL IDENTITY(1,1),
	CarModelID INT,
	Modification VARCHAR(16),
	Code VARCHAR(16),
	EngineType VARCHAR(16),
	EngineModel VARCHAR(16),
	EngineCapacity VARCHAR(16),
	EnginePower INT,
	DriveType VARCHAR(16),
	BeginOfExploitation INT,
	EndOfExploitation INT,
	PRIMARY KEY (ID)
);

ALTER TABLE CarInfo_T ADD CONSTRAINT CarInfo_T_fk0 FOREIGN KEY (CarModelID) REFERENCES CarModel_T(ID);

CREATE TABLE Category_T (
	ID INT NOT NULL IDENTITY(1,1),
	CarInfoID INT,
	Name VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE Category_T ADD CONSTRAINT Category_T_fk0 FOREIGN KEY (CarInfoID) REFERENCES CarInfo_T(ID);

CREATE TABLE SubCategory_T (
	ID INT NOT NULL IDENTITY(1,1),
	CategoryID INT,
	Name VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE SubCategory_T ADD CONSTRAINT SubCategory_T_fk0 FOREIGN KEY (CategoryID) REFERENCES Category_T(ID);

CREATE TABLE SubSubCategory_T (
	SubCategoryID INT,
	Name VARCHAR(32),
	ID INT NOT NULL IDENTITY(1,1),
	PRIMARY KEY (ID)
);

ALTER TABLE SubSubCategory_T ADD CONSTRAINT SubSubCategory_T_fk0 FOREIGN KEY (SubCategoryID) REFERENCES SubCategory_T(ID);

CREATE TABLE Item_T (
	SubSubCategoryID INT,
	Description VARCHAR(32),
	ID INT NOT NULL IDENTITY(1,1),
	ItemProducerID INT,
	Name VARCHAR(32),
	Reference VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE Item_T ADD CONSTRAINT Item_T_fk0 FOREIGN KEY (SubSubCategoryID) REFERENCES SubSubCategory_T(ID);

CREATE TABLE ItemInfo_T (
	ItemID INT,
	ID INT NOT NULL IDENTITY(1,1),
	InfoName VARCHAR(16),
	InfoValue VARCHAR(16),
	PRIMARY KEY (ID)
);

ALTER TABLE ItemInfo_T ADD CONSTRAINT ItemInfo_T_fk0 FOREIGN KEY (ItemID) REFERENCES Item_T(ID);

CREATE TABLE ItemProducer_T (
	ID INT NOT NULL IDENTITY(1,1),
	Name VARCHAR(32),
	Address VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE Item_T ADD CONSTRAINT Item_T_fk1 FOREIGN KEY (ItemProducerID) REFERENCES ItemProducer_T(ID);

CREATE TABLE Price_T (
	ID INT NOT NULL IDENTITY(1,1),
	ItemID INT,
	UnitCost INT,
	[Time] TIME,
	PRIMARY KEY (ID)
);

ALTER TABLE Price_T ADD CONSTRAINT Price_T_fk0 FOREIGN KEY (ItemID) REFERENCES Item_T(ID);

CREATE TABLE OrderItem_T (
	ID INT NOT NULL IDENTITY(1,1),
	OrderID INT,
	PriceID INT,
	Count INT,
	PRIMARY KEY (ID)
);

ALTER TABLE OrderItem_T ADD CONSTRAINT OrderItem_T_fk1 FOREIGN KEY (PriceID) REFERENCES Price_T(ID);

CREATE TABLE Order_T (
	ID INT NOT NULL IDENTITY(1,1),
	UserID INT,
	[Time] INT,
	Cost INT,
	Status INT,
	PRIMARY KEY (ID)
);

ALTER TABLE OrderItem_T ADD CONSTRAINT OrderItem_T_fk0 FOREIGN KEY (OrderID) REFERENCES Order_T(ID);

CREATE TABLE User_T (
	ID INT NOT NULL IDENTITY(1,1),
	Login VARCHAR(32),
	Password VARCHAR(32),
	PRIMARY KEY (ID)
);

ALTER TABLE Order_T ADD CONSTRAINT Order_T_fk0 FOREIGN KEY (UserID) REFERENCES User_T(ID);

CREATE TABLE Trade_T (
	ID INT NOT NULL IDENTITY(1,1),
	Count INT,
	Price INT,
	Description VARCHAR(256),
	[Time] TIME,
	Status INT,
	UserID INT,
	ItemID INT,
	PRIMARY KEY (ID)
);

ALTER TABLE Trade_T ADD CONSTRAINT Trade_T_fk0 FOREIGN KEY (UserID) REFERENCES User_T(ID);
ALTER TABLE Trade_T ADD CONSTRAINT Trade_T_fk1 FOREIGN KEY (ItemID) REFERENCES Item_T(ID);
