//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo_T
    {
        public CarInfo_T()
        {
            this.Category_T = new HashSet<Category_T>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CarModelID { get; set; }
        public string Modification { get; set; }
        public string Code { get; set; }
        public string EngineType { get; set; }
        public string EngineModel { get; set; }
        public string EngineCapacity { get; set; }
        public Nullable<int> EnginePower { get; set; }
        public string DriveType { get; set; }
        public Nullable<int> BeginOfExploitation { get; set; }
        public Nullable<int> EndOfExploitation { get; set; }
    
        public virtual CarModel_T CarModel_T { get; set; }
        public virtual ICollection<Category_T> Category_T { get; set; }
    }
}
