//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel_T
    {
        public CarModel_T()
        {
            this.CarInfo_T = new HashSet<CarInfo_T>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CarProducerID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CarInfo_T> CarInfo_T { get; set; }
        public virtual CarProducer_T CarProducer_T { get; set; }
    }
}
