//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarProducer_T
    {
        public CarProducer_T()
        {
            this.CarModel_T = new HashSet<CarModel_T>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CarModel_T> CarModel_T { get; set; }
    }
}
