//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_T
    {
        public Order_T()
        {
            this.OrderItem_T = new HashSet<OrderItem_T>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual User_T User_T { get; set; }
        public virtual ICollection<OrderItem_T> OrderItem_T { get; set; }
    }
}
