//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory_T
    {
        public SubCategory_T()
        {
            this.SubSubCategory_T = new HashSet<SubSubCategory_T>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Name { get; set; }
    
        public virtual Category_T Category_T { get; set; }
        public virtual ICollection<SubSubCategory_T> SubSubCategory_T { get; set; }
    }
}
