//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_T
    {
        public int ID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual Item_T Item_T { get; set; }
        public virtual User_T User_T { get; set; }
    }
}
