//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMotion
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_T
    {
        public User_T()
        {
            this.Order_T = new HashSet<Order_T>();
            this.Trade_T = new HashSet<Trade_T>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Order_T> Order_T { get; set; }
        public virtual ICollection<Trade_T> Trade_T { get; set; }
    }
}
